[default]
description = "Default permissions for the Samsung Tizen native plugin"
permissions = [
  "allow-tizen-connect",
  "allow-tizen-install",
  "allow-tizen-uninstall",
  "allow-tizen-list-apps",
  "allow-tizen-get-prop",
  "allow-tizen-get-device-info",
  "allow-tizen-launch",
  "allow-tizen-kill",
  "allow-tizen-debug",
  "allow-tizen-get-duid",
  "allow-tizen-shell",
  "allow-tizen-daemon-command",
  "allow-tizen-get-app-version",
  "allow-tizen-install-tizen-brew",
  "allow-tizen-tizen-brew-device-details",
]
